#!/bin/sh

set -e

if [ "$1" = configure ]; then
  update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css \
    gdm3.css /usr/share/themes/Workspaces-dark/gnome-shell/gnome-shell.css 15
fi



